name: AtlasAssorted
main: com.atlasmc.atlasassorted.AtlasAssorted
version: 0.1.1
commands:
   website:
      description: Creates an account for you on the website!
      usage: /website
      default: true
   help:
      description: Give you info you'll need for your time on atlas!
      usage: /help
      default: true
   soulbound:
      description: Makes an item soulbound
      usage: /soulbound
      default: op
   purgatory:
      description: Sends a player to purgatory
      usage: /purgatory <level> <player>
      default: op
   assorted:
      description: Assorted Atlas commands
      usage: /assorted help
      default: op
      